# Generated by Django 6.1.1 on 2026-10-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_preco_custo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Bebidas', 'Bebidas'), ('Alimentos', 'Alimentos'), ('Limpeza', 'Limpeza'), ('Eletrónicos', 'Eletrónicos'), ('Outros', 'Outros')], default='Outros', max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
