# Generated by Django 6.1.1 on 2026-10-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_caixaturno'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicovenda',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.caixaturno'),
        ),
    ]
