# Generated by Django 6.1.1 on 2026-10-09 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historicovenda_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicovenda',
            name='venda_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
