# Generated by Django 6.1.1 on 2026-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicovenda_venda_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicovenda',
            name='forma_pagamento',
            field=models.CharField(default='dinheiro', max_length=20),
        ),
    ]
